require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/*'
    - 'config/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/seeds/*'

Metrics/BlockLength:
  Exclude:
    - 'db/*'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/*jwt_denylist*'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
